version: '3.8'

services:
  mongo-db:
    image: mongo:6.0.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ./mongo-data:/data/db
    ports:
      - 27017:27017

  # postgres-db:
  #   image: postgres:15.3
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 123456
  #     POSTGRES_DB: my-db
  #   volumes:
  #     - ./postgres-data:/var/lib/postgresql/dat
  #   ports:
  #     - 5432:5432
